const UserActionTypes = {
    GET_USER_DATA_START: 'GET_USER_DATA_START',
    GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
    GET_USER_DATA_FAIL: 'GET_USER_DATA_FAIL',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
}
export default UserActionTypes