const UserActionTypes = {
    GET_USER_DATA_START: 'GET_USER_DATA_START',
    GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
    GET_USER_DATA_FAIL: 'GET_USER_DATA_FAIL',
    GET_COMPANYDETAILS_START: 'GET_COMPANYDETAILS_START',
    GET_COMPANYDETAILS_SUCCESS: 'GET_COMPANYDETAILS_SUCCESS',
    GET_COMPANYDETAILS_FAIL: 'GET_COMPANYDETAILS_FAIL',
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',
    // GET_ROOT_USER_COMPANY_START: 'GET_ROOT_USER_COMPANY_START',
    // GET_ROOT_USER_COMPANY_SUCCESS: 'GET_ROOT_USER_COMPANY_SUCCESS',
    // GET_ROOT_USER_COMPANY_FAIL: 'GET_ROOT_USER_COMPANY_FAIL',
    // ADD_ROOT_USER_INFO_START: 'ADD_ROOT_USER_INFO_START',
    // ADD_ROOT_USER_INFO_SUCCESS: 'ADD_ROOT_USER_INFO_SUCCESS',
    // ADD_ROOT_USER_INFO_FAIL: 'ADD_ROOT_USER_INFO_FAIL'
}
export default UserActionTypes