const ticketsActionTypes = {
    GET_TICKETS_DATA_START: 'GET_TICKETS_DATA_START',
    GET_TICKETS_DATA_SUCCESS: 'GET_TICKETS_DATA_SUCCESS',
    GET_TICKETS_DATA_FAIL: 'GET_TICKETS_DATA_FAIL',
    GET_TICKET_INFO_START: 'GET_TICKET_INFO_START',
    GET_TICKET_INFO_SUCCESS: 'GET_TICKET_INFO_SUCCESS',
    GET_TICKET_INFO_FAIL: 'GET_TICKET_INFO_FAIL',
    CLEAR_TICKET_INFO: 'CLEAR_TICKET_INFO'
}
export default ticketsActionTypes